# Generated by Django 4.2.5 on 2023-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
