# Generated by Django 4.2.5 on 2023-12-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0002_post_canonical_url_post_is_indexed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
