# Generated by Django 4.2.5 on 2024-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0003_faqcategoryconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstorage',
            name='privacy_policy',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commonstorage',
            name='terms_of_use',
            field=models.JSONField(default=list),
        ),
    ]
