# Generated by Django 4.2.5 on 2023-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0004_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
