# Generated by Django 4.2.5 on 2024-01-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0006_commonstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
