# Generated by Django 4.2.5 on 2024-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0007_post_focus_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstorage',
            name='about_page',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commonstorage',
            name='blogs_page',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commonstorage',
            name='categories_page',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commonstorage',
            name='home_page',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commonstorage',
            name='redirects',
            field=models.JSONField(default=list),
        ),
    ]
