# Generated by Django 4.2.5 on 2024-01-23 14:17

import dirtyfields.dirtyfields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0008_commonstorage_about_page_commonstorage_blogs_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('is_permanent', models.BooleanField(default=False)),
                ('old', models.CharField(blank=True, max_length=255)),
                ('new', models.CharField(blank=True, max_length=255)),
                ('extras', models.JSONField(default=list)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
