# Generated by Django 4.2.5 on 2024-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0011_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='dofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='nofollow',
            field=models.BooleanField(default=False),
        ),
    ]
