# Generated by Django 4.2.5 on 2024-04-06 11:29

import autoslug.fields
import contentio.utils
import dirtyfields.dirtyfields
from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0012_sponsor_dofollow_sponsor_nofollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=contentio.utils.get_post_slug, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=contentio.utils.get_faq_media_path_prefix)),
                ('summary', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number is higher priority.')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
