# Generated by Django 4.2.5 on 2024-04-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0013_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
    ]
