# Generated by Django 4.2.5 on 2023-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INITIATOR', 'Initiator'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='INITIATOR', max_length=30),
        ),
    ]
