# Generated by Django 4.2.5 on 2023-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
