# Generated by Django 4.2.5 on 2023-11-18 04:33

import core.utils
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_image_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=core.utils.get_user_media_path_prefix, verbose_name='Image'),
        ),
    ]
