# Generated by Django 4.2.5 on 2023-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='hello', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
