# Generated by Django 4.2.5 on 2023-11-13 13:08

import core.utils
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_exp_user_iid_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='jti',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=core.utils.get_user_media_path_prefix, verbose_name='Picture'),
        ),
    ]
