# Generated by Django 4.2.5 on 2023-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_iat_user_jti_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iid',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
