# Generated by Django 4.2.5 on 2023-10-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='tool',
        ),
    ]
