# Generated by Django 4.2.5 on 2023-10-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
    ]
