# Generated by Django 4.2.5 on 2023-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0002_rating_user_savedtool_love_tool_savedtool_save_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
