# Generated by Django 4.2.5 on 2023-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0002_toolsconnector_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
