# Generated by Django 4.2.5 on 2024-05-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0002_bestalternativetool_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretool',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.subcategory'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_category_featured',
            field=models.BooleanField(default=False),
        ),
    ]
