# Generated by Django 4.2.5 on 2023-10-26 01:37

import catalogio.utils
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0003_remove_subcategory_category_toolscategoryconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogio.utils.get_category_media_path_prefix, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogio.utils.get_subategory_media_path_prefix, verbose_name='Avatar'),
        ),
    ]
