# Generated by Django 4.2.5 on 2024-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0003_featuretool_subcategory_tool_is_category_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
