# Generated by Django 4.2.5 on 2024-06-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentio', '0002_post_user'),
        ('catalogio', '0004_deal_is_hot_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentio.faq'),
        ),
    ]
