# Generated by Django 4.2.5 on 2023-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0004_category_image_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
