# Generated by Django 4.2.5 on 2024-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0005_subcategory_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
