# Generated by Django 4.2.5 on 2023-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0005_category_alt_subcategory_alt_tool_alt_featuretool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretool',
            name='tool',
        ),
        migrations.AddField(
            model_name='featuretool',
            name='feature_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
