# Generated by Django 4.2.5 on 2023-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0005_category_alt_subcategory_alt_tool_alt_featuretool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretool',
            name='slug',
        ),
        migrations.AlterField(
            model_name='featuretool',
            name='tool',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
