# Generated by Django 4.2.5 on 2023-12-17 10:48

import autoslug.fields
import catalogio.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0006_remove_featuretool_slug_alter_featuretool_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretool',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from=catalogio.utils.get_feature_slug, unique=True),
            preserve_default=False,
        ),
    ]
