# Generated by Django 4.2.5 on 2023-12-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0006_remove_featuretool_tool_featuretool_feature_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='discoard_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='email_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
