# Generated by Django 4.2.5 on 2024-08-02 19:17

import catalogio.models
import catalogio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0006_subcategory_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to=catalogio.utils.get_category_media_path_prefix, validators=[catalogio.models.FileExtensionValidator()], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, upload_to=catalogio.utils.get_subategory_media_path_prefix, validators=[catalogio.models.FileExtensionValidator()], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.FileField(blank=True, upload_to=catalogio.utils.get_tools_media_path_prefix, validators=[catalogio.models.FileExtensionValidator()], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=catalogio.utils.get_tools_media_path_prefix, validators=[catalogio.models.FileExtensionValidator()], verbose_name='Logo'),
        ),
    ]
