# Generated by Django 4.2.5 on 2023-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0007_featuretool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
