# Generated by Django 4.2.5 on 2023-12-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0007_tool_discoard_url_tool_email_url_tool_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='pricing',
            field=models.CharField(choices=[('FREE', 'Free'), ('FREEMIUM', 'Freemium'), ('FREE_TRIAL', 'Free Trial'), ('PREMIUM', 'Premium'), ('CONTACT_FOR_PRICING', 'Contact for Pricing')], default='CONTACT_FOR_PRICING', max_length=30),
        ),
    ]
