# Generated by Django 4.2.5 on 2024-01-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0008_alter_tool_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretool',
            name='feature_tools',
        ),
        migrations.AddField(
            model_name='featuretool',
            name='custom_field',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='featuretool',
            name='feature_tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogio.tool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='do_follow_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing_url',
            field=models.URLField(blank=True),
        ),
    ]
