# Generated by Django 4.2.5 on 2024-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0009_remove_featuretool_feature_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretool',
            name='in_pages',
            field=models.JSONField(default=list),
        ),
    ]
