# Generated by Django 4.2.5 on 2024-01-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0010_featuretool_in_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='is_indexed',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='do_sponsor_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
