# Generated by Django 4.2.5 on 2024-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0013_remove_subcategory_is_indexed_subcategory_is_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_suggession',
            field=models.BooleanField(default=False),
        ),
    ]
