# Generated by Django 4.2.5 on 2024-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0015_tool_logo_tool_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
