# Generated by Django 4.2.5 on 2024-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0019_bestalternativetool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tophundredtools',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
