# Generated by Django 4.2.5 on 2024-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0021_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='coupon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
