# Generated by Django 4.2.5 on 2024-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0022_alter_deal_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='discout',
            field=models.IntegerField(default=0),
        ),
    ]
