# Generated by Django 4.2.5 on 2024-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0023_tool_discout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='coupon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
