# Generated by Django 4.2.5 on 2024-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0024_tool_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
